#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=28
PANEL_FONT="-*-terminus-*-*-*-*-20-*-*-*-*-*-*-*"
# PANEL_FONT="-*-hack-*-*-*-*-24-*-*-*-*-*-*-*"
# PANEL_FONT="-*-source code pro-*-*-*-*-24-*-*-*-*-*-*-*"
PANEL_WM_NAME=bspwm_panel

export PANEL_FIFO PANEL_HEIGHT PANEL_FONT PANEL_WM_NAME

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

xtitle -sf 'T%s\n' > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
while true; do
  # wm="${wm}%{F${FG}}%{B${BG}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
  # date "+S%%{A:~/bin/calendar.bash:}%a %F %R%%{A}"
  date '+S%a %F %R'
  seconds=$(date +%-S)
  seconds_to_full_minute=$(( 60 - $seconds ))
  sleep $seconds_to_full_minute
done > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

. ./panel_colors

./panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -u 4 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &


wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
