#! /bin/sh

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

xrandr | grep -q 2560x1440 && ~/.screenlayout/peaq.sh
[ $(xrandr | grep -wc connected) -eq 3 ] && ~/.screenlayout/2x-acer.sh

bspc config border_width         3
bspc config focused_border_color '#FF0000'
bspc config active_border_color  '#0000FF'
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Firefox desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a 'Alacritty:*:Calendar' state=floating follow=on
bspc rule -a 'Alacritty:*:Cheatsheet' state=floating follow=on
bspc rule -a 'Alacritty:*:Power menu' state=floating follow=on
bspc rule -a 'Alacritty:*:Screenshot menu' state=floating follow=on
bspc rule -a 'Alacritty:*:Screen menu' state=floating follow=on
bspc rule -a 'st-256color:*:vim' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# pkill -x panel > /dev/null ; cd ~/.config/bspwm/panel && ./panel &
~/.config/bspwm/restart-bspwmpanel.sh &
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/bspwm_sxhkdrc &

~/.config/bspwm/autostart.sh > ~/.bspwm.log
